- name: Create Deployment Service On Kubernetes In Production VM
  hosts: azure

  vars:
    myResourceGroup: DevOps
    myVM: productionVM

  tasks:
  - name: Create Service
    command: kubectl apply -f /home/cmackie95/kubectl_service_deployment.yml